name: nytimes
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

isar_version: &isar_version 3.1.0


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  json_annotation: ^4.8.1
  dep_gen: ^1.0.11
  
  flutter_svg: 1.1.6
  shimmer: 2.0.0
  cached_network_image: ^3.2.3
  freezed_annotation: 2.2.0
  easy_localization: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  auto_route: ^7.1.0
  isar: *isar_version
  path_provider: ^2.0.15
  isar_flutter_libs: *isar_version
  connectivity_plus: ^4.0.0
  webview_flutter: ^4.2.0
  webview_flutter_android: ^3.7.0
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_background_service_ios: ^2.4.0
  permission_handler: ^10.2.0
  flutter_local_notifications: ^9.5.1
  flutter_keyboard_visibility: ^5.4.3
  workmanager: ^0.5.1
  marquee: ^2.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

  # кодогенерация
  build_runner: 2.3.3
  json_serializable: 6.6.0
  freezed: ^2.3.3
  auto_route_generator: ^7.0.0
  isar_generator: *isar_version

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/languages/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: CustomIcons
      fonts: 
        - asset: assets/icons/icomoon.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_black.ttf
          weight: 900
        - asset: assets/fonts/inter_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/inter_bold.ttf
          weight: 700
        - asset: assets/fonts/inter_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_light.ttf
          weight: 300
        - asset: assets/fonts/inter_extra_light.ttf
          weight: 200
        - asset: assets/fonts/inter_thin.ttf
          weight: 100

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
